# This is a Docker image for the Drone CI system. 
# Use the following command to start the container: 
#    docker run -p 127.0.0.1:80:80 -t drone/drone 

FROM arm64v8/golang:1.9.2
ENV DRONE_SERVER_PORT :80
RUN go get github.com/drone/drone/cmd/...

EXPOSE 8000 9000 80 443
ENV DRONE_DATABASE_DATASOURCE /var/lib/drone/drone.sqlite 
ENV DRONE_DATABASE_DRIVER sqlite3 
VOLUME ["/var/lib/drone"]
ENTRYPOINT ["/go/bin/drone-server"]
