FROM arm64v8/golang:1.9.2-alpine
MAINTAINER Frederic Logier <fredix@protonmail.com>

EXPOSE 8000 9000 80 443

RUN apk add -U --no-cache ca-certificates git sqlite-dev build-base

RUN go get github.com/drone/drone/cmd/drone-server

ENV DATABASE_DRIVER=sqlite3
ENV DATABASE_CONFIG=/var/lib/drone/drone.sqlite
ENV GODEBUG=netdns=go
ENV XDG_CACHE_HOME /var/lib/drone

ENTRYPOINT ["drone-server"]

