# This is a Docker image for the Drone CI system. 
# Use the following command to start the container: 
#    docker run -p 127.0.0.1:80:80 -t drone/drone 
# FROM arm32v7/golang:1.9.2

FROM golang:1.9.2
RUN go get github.com/drone/drone/cmd/...

EXPOSE 3000
VOLUME ["/var/lib/drone"]
ENTRYPOINT ["/go/bin/drone-agent"]
